name: remove all old actions

on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:

      - name: download remove_all_actions
        run: |
          sudo curl -L -o '/usr/bin/remove_all_actions' 'https://raw.githubusercontent.com/invalidunit/action/main/remove_all_actions'
          sudo chmod -R 0755 '/usr/bin/remove_all_actions'

      - name: remove all old actions
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          remove_all_actions
